### ISSUE TITLE
Infinite scrolling seems to be broken

### ISSUE THREAD

**Issue by mikkokotila** [Lotus-King-Research/Padma-Frontend#102]
This query brings many results, but looks like only four https://padma.io/#/search_texts?query=%E0%BD%A6%E0%BD%BA%E0%BD%98%E0%BD%A6%E0%BC%8B

**Comment by rabtenster** [comment]
its from the backend that I am getting alot of duplicate results, same title repeated so many times. its an backend issue.
![Screenshot 2022-01-24 at 4 57 44 PM](https://user-images.githubusercontent.com/10251363/150775319-4eee599a-53b
![Screenshot 2022-01-24 at 4 59 07 PM](https://user-images.githubusercontent.com/10251363/150775350-bcd22fef-d5c0-46a7-b924-34064e50cedb.png)
2-4080-82fa-7ed96ae2987d.png)
