### ISSUE TITLE
Add ability to search from descriptions

### ISSUE THREAD

**Issue by mikkokotila** [Lotus-King-Research/Padma-Frontend#168]
## Background

So far it is possible to search based on keys (Tibetan words), here we will make it possible to also search based on values (descriptions for Tibetan words). It will work similarly to `partial`, `fuzzy`, and `similar` in the sense that it will force to select a single dictionary where the search is performed. But it will be different in the sense that instead of becoming available in the search button, it becomes available as its own menu item.

## How will it work? 

- [x] Add back the navigation with items `Tibetan`, `Description`
- [x] `Tibetan` does what the dictionary does now
- [x] `Description` works otherwise the same as `Tibetan` but it will look for a match from descriptions
- [x] `Description` is enabled through `matching=description` argument in the API
- [x] Once `Description` is enabled, the search button only has `Partial match` option
- [x] Upon selecting `Description`, the prompt for selecting just one dictionary is shown

**Comment by rabtenster** [comment]
@mikkokotila  Once Description is enabled, the search button only has Partial match option : This line is confusing as currently we have four matching modes where partial is one, now when description is also enabled by adding a new matching mode , then having partial match option for description confuses as matching = description and not partial. Maybe I didn't get it properly can you shed some more light on it.
