### ISSUE TITLE
when adding more dictionaries, no search is made

### ISSUE THREAD

**Issue by mikkokotila** [Lotus-King-Research/Padma-Frontend#178]
Imagine the situation:

1) You are in `exact match`
2) You have one dictionary selected
3) You make the search and do not get results
4) You add the rest of the dictionaries

At this point you expect the search to be performed again (because there are now more dictionaries selected) but that will not happen, nothing will happen when you hit search.

**Comment by rabtenster** [comment]
@mikkokotila so basically there can be three scenarios when you are in "exact match":

1) when you get a search result and then you add more dictionaries and click on search(exact match), you will get new results as search is performed again.

2) when you get no search results, you add more dictionaries and click on search(exact match), at this point you might get results as more dictionaries are added but we don't want it to perform search again right? (is that what you are saying ?)

3) or whenever you add more dictionaries and if the search query is same then don't perform search again irrespective of whether you get search results or not.

so which cases you want me to do. 1 and 2 or 3 ?

**Comment by mikkokotila** [comment]
> 1. when you get a search result and then you add more dictionaries and click on search(exact match), you will get new results as search is performed again

This is valid. To further clarify, the results will be returned always as per the selected dictionaries. So if I add two more dictionaries, then the results will not include those too.

> 2. when you get no search results, you add more dictionaries and click on search(exact match), at this point you might get results as more dictionaries are added but we don't want it to perform search again right? (is that what you are saying ?)

We do want the search to be performed again whenever more dictionaries are selected. Always. Right now it does not do that. Right now there is the bug which prevents this from happening. That is what we have to fix.

> 3. or whenever you add more dictionaries and if the search query is same then don't perform search again irrespective of whether you get search results or not.

This is non-sensical. This is the way it works now. This is the bug we want to fix.

**Comment by rabtenster** [comment]
@mikkokotila  I mentioned the above three points because this bug doesn't exist so I thought you want to change the status quo, I tested both on  locally  and staging.padma.io , It is performing search again if you select or add more dictionaries irrespective of whether you get search results or not.

**Comment by mikkokotila** [comment]
in LKT it does not work like you say it works

**Comment by rabtenster** [comment]
@mikkokotila  The above issue exist only in padma.io  which is running the old version as things are not being updated from staging.padma.io
The same issue doesn't exist in the staging.padma.io
I believe all the issues and fixes should be tested on staging.padma.io and not on padma.io
the whole idea of staging is to fix the issue locally and then pushed to staging for further testing and then finally  to production which is padma.io in this case. I often get confused when you sometimes test from staging and sometimes from padma.io whereas everything should be tested from staging.io no? as All the latest changes and fixes are on staging and not in production.

**Comment by mikkokotila** [comment]
The way the system works is very simple:

- Staging is for testing BEFORE merging PR
- Production is for testing AFTER merging PR

This is the standard way of working across all projects. So now it is completely clear and there should be no reason to be confused. 

But ok yes, looks like currently what we have in Staging is not the same version as we have in Production. So I will fix that first, and then we can see where are.
