### ISSUE TITLE
Frontend new designs

### ISSUE THREAD

**Issue by mikkokotila** [Lotus-King-Research/Padma-Frontend#32]
We have a candidate for revamping the look and feel. 

https://www.figma.com/file/6Q91bSWao7kHYeQefbSqZz/Padma?node-id=0%3A1

**Comment by blahmonkey** [comment]
Nice, simple

**Comment by mikkokotila** [comment]
Here are the assets:

[padma-assets.zip](https://github.com/Lotus-King-Research/Padma-Frontend/files/5750874/padma-assets.zip)

> Nice, simple. How would it be on mobile?

I think:

- leave left-half out
- place a single-line textbox for the search to the right from the menu
- leave everything else as it is

That seems like a good compromise for now. What do you think?

**Comment by blahmonkey** [comment]
It may prove a bit narrow for the menu + search bar. 

So maybe the search bar would come to the next row, below the menu. And Logo also placed in a suitable position.

We can try and see. Its been a long time since I looked at the codebase. Will take a look once all activities here settle down a bit.

**Comment by mikkokotila** [comment]
Mobile mocks:

[padma-assets2.zip](https://github.com/Lotus-King-Research/Padma-Frontend/files/5765092/padma-assets2.zip)

**Comment by mikkokotila** [comment]
Looks like the actual design mocks are not included in the zip files. Also, some of the GUIs are missing. The one for dictionary search results and text search results are here: 

https://www.figma.com/file/6Q91bSWao7kHYeQefbSqZz/Padma?node-id=0%3A1

So work can be started with those, I will get the missing ones done in the meantime :)
