### ISSUE TITLE
CI to build release packages

### ISSUE THREAD

**Issue by blahmonkey** [Lotus-King-Research/Padma-Frontend#5]
Scripting needed so that we can build to a release folder

**Comment by mikkokotila** [comment]
[Here is a link](https://github.com/mikkokotila/Padma/blob/master/.github/workflows/Deploy.yml) to the current CI for Padma(-Backend). 

Some server configuration must be made as well (run frontend container as systemd service). Then we can remove all the views related parts from Padma-Backend.

**Comment by blahmonkey** [comment]
Cool. Lets sort out some of the pressing issues and then get to that (styling fixes etc. can come later, but bugs should be fixed first)

**Comment by blahmonkey** [comment]
Lets get the code signing in place before we do the CI for release package builds. I will add a separate issue for building the web distribution (to autodeploy to staging or production)
