### ISSUE TITLE
Improvements to Frontend designs

### ISSUE THREAD

**Issue by mikkokotila** [Lotus-King-Research/Padma-Frontend#57]
1) We want to have a button which is below the text area, which says “lookup”

![Screenshot 2021-11-22 at 11 44 38](https://user-images.githubusercontent.com/7943188/142888531-41b70a7a-333c-440d-92ee-1fe6fecc2008.png)

2) For each individual research, we want to have a label before it (so for example in above “life-force” will be following the label, where the label says the name of the dictionary. The label should be in like “pill” shape, as later we want to introduce two UX functionality to it 1) there will later small x, and if that is clicked then from the current results that dictionary results will be removed for all tokens, and 2) when the main area of the label is clicked, all other are hidden except that dictionary, and when it is clicked again, the rest are shown again. But for now we just want to introduce the label. It should be quite subtle, as the main content is the result and not the label.

![Screenshot 2021-11-22 at 11 48 38](https://user-images.githubusercontent.com/7943188/142888577-c00b947e-b0f8-4299-9c19-52bb00857efd.png)

3) Can we have a better way to use space for results, as there will be really many and we don’t do any sorting based on which is most relevant and so on like search engines do? We just show them all. Better if we can show a little bit more results in a single view.

4) We want to have pagination for the results. 

![Screenshot 2021-11-22 at 11 50 24](https://user-images.githubusercontent.com/7943188/142888611-3bcec5a9-df24-4885-9c52-4e8ffec5f0d6.png)

5) When the double arrow is hit, we want to load the entire text, but we want to show it as infinite scroll, so that just one page full is shown and there is indiation to scroll and then it just keeps showing more as scrolling takes place. So really, the double arrow is to say “toggle infinite scroll” actually. 

![Screenshot 2021-11-22 at 11 51 57](https://user-images.githubusercontent.com/7943188/142888666-831a9161-f559-48f1-a16a-714f4c566a2d.png)

**Comment by blahmonkey** [comment]
I think sidrun has done this, so this can be closed?
