### ISSUE TITLE
extra parameter in `search_texts` results page queries

### ISSUE THREAD

**Issue by mikkokotila** [Lotus-King-Research/Padma-Frontend#65]
Looks like currently frontend is passing one redundant query parameter in this `request http://localhost:8080/#/render_text?title=Terdzo-ZHI-038&text_title=%E0%BD%98%E0%BD%84%E0%BD%A0%E0%BC%8B%E0%BD%91%E0%BD%96%E0%BD%84%E0%BC%8B%E0%BD%A2%E0%BD%B2%E0%BD%93%E0%BC%8B%E0%BD%86%E0%BD%BA%E0%BD%93%E0%BC%8B%E0%BD%A0%E0%BD%96%E0%BD%A2%E0%BC%8B%E0%BD%96%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%A3%E0%BD%82%E0%BC%8B%E0%BD%A3%E0%BD%BA%E0%BD%93%E0%BC%8B%E0%BD%82%E0%BD%A6%E0%BD%A3%E0%BC%8B%E0%BD%96%E0%BD%A2%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BE%A1%E0%BD%BA%E0%BD%96%E0%BD%A6%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%91%E0%BD%82%E0%BD%BA%E0%BC%8B%E0%BD%A3%E0%BD%BA%E0%BD%82%E0%BD%A6%E0%BC%8B%E0%BD%93%E0%BD%BC%E0%BD%A2%E0%BC%8B%E0%BD%96%E0%BD%B4%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%82%E0%BD%9F%E0%BD%B2%E0%BC%8B%E0%BD%A0%E0%BD%96%E0%BD%A2%E0%BC%8B&start=24&end=26` 

(this happens when you click the two arrows in result page for search_texts)

The extra parameter here is `text_title`. It can be removed.

**Comment by blahmonkey** [comment]
@rabtenster Please check and remove if needed now
