### ISSUE TITLE
Grouping of results in `search_texts`

### ISSUE THREAD

**Issue by mikkokotila** [Lotus-King-Research/Padma-Frontend#66]
We get now more than one result per text, so it will make sense to group them based on the text title.

**Comment by blahmonkey** [comment]
@mikkokotila I think this isnt present in the new design?

**Comment by mikkokotila** [comment]
> @mikkokotila I think this isnt present in the new design?

That's right, it's not. Will have to get the design for this first.

**Comment by mikkokotila** [comment]
As the first step, I will get the designs for this. Will make it `first` once the designs are available.
