### ISSUE TITLE
Signed apps

### ISSUE THREAD

**Issue by blahmonkey** [Lotus-King-Research/Padma-Frontend#8]
Mac, windows, linux

Need ? Cost? Process?

**Comment by blahmonkey** [comment]
https://www.electronjs.org/docs/tutorial/code-signing#:~:text=While%20it%20is%20possible%20to,the%20execution%20of%20unsigned%20applications.&text=If%20you%20are%20building%20an,it%20should%20be%20code%2Dsigned.

windows - ~$200/yr
mac - ~$200/yr

Only organizations can get a certificate.

> While it is possible to distribute unsigned apps, it is not recommended. Both Windows and macOS will, by default, prevent either the download or the execution of unsigned applications.

**Comment by mikkokotila** [comment]
Ah ok so this is quite important to do.

**Comment by mikkokotila** [comment]
> Only organizations can get a certificate.

Did I understand correct, individuals are not able to get this one at all?

**Comment by blahmonkey** [comment]
Looked this up, I was wrong, individuals can get one too. Apple is fixed price, Microsoft is via reseller so different pricing, have to shop around. The link has good info.
