### ISSUE TITLE
Dictionary results dropdown count sometimes inaccurate

### ISSUE THREAD

**Issue by blahmonkey** [Lotus-King-Research/Padma-Frontend#89]
When the results comes from multiple dictionaries, clicking X on some dictionary in a test caused the results from that dictionary to disappear, but the dropdown still showed same number of dictionaries

This may need to be tested a few times to reproduce

**Comment by blahmonkey** [comment]
Also we should capitalize the dictionary names (all words) - ignore the figma one for this

**Comment by rabtenster** [comment]
@mikkokotila I can't reproduce this bug, can you still see the same?

**Comment by mikkokotila** [comment]
Now it's working :)
