### ISSUE TITLE
Add Smartlook

### ISSUE THREAD

**Issue by mikkokotila** [Lotus-King-Research/Padma-Frontend#93]
Will be great if we can have [Smartlook](https://www.smartlook.com/) in place before we roll out. That way we capture everything from the onset :)

**Comment by blahmonkey** [comment]
Ah yes, forgot it in the review process and fixing ssl/npm issues today :-)

**Comment by blahmonkey** [comment]
As first task, this is just adding smartlook to the project ? @mikkokotila 

I think smartlook client allows like custom events to be sent, I think we dont do any of that right now yet?

**Comment by blahmonkey** [comment]
Added this

@mikkokotila How do we test this? I just added this the same way as the script / tag that you showed, but using the npm module

**Comment by blahmonkey** [comment]
PS: Check readme. This adds a new env variable needed for use here, and also should add to CI etc
