### ISSUE TITLE
Does the CI have to change for infra deploy?

### ISSUE THREAD

**Issue by mikkokotila** [Lotus-King-Research/Padma-Frontend#94]
Based on this it looks like we now have to deploy the keys as part of the infra deploy?

![Screenshot 2022-01-18 at 11 29 14](https://user-images.githubusercontent.com/7943188/149909344-c5dac6a1-b5be-443e-9959-8ce0be6bfa46.png)

**Comment by mikkokotila** [comment]
Or actually not infra CI, but the `Padma-Frontend` CI, so that it ingest the keys from Github secrets onto the image?

**Comment by blahmonkey** [comment]
I think we just need to not use these during the production build because anyway you will make the SSL certificates yourself

Need to update the vueconfig.js for this. Will do it along with smartlook as the 2 final microtasks of currently draft PR.

**Comment by blahmonkey** [comment]
Updated on the PR, should be fixed
